export const accessories = [
  {
    id: 1,
    name: "Premium Floor ...Mats",
    price: 4999,
    category: "interior",
    model: "all",
    image: new URL("../../assets/floormat.jpg", import.meta.url).href,
    rating: 4.5,
    featured: true,
  },
  {
    id: 2,
    name: "Roof Rack System",
    price: 12999,
    category: "exterior",
    model: "safari",
    image: new URL("../../assets/safaritopstand.jpg", import.meta.url).href,

    rating: 4.2,
    featured: false,
  },
  {
    id: 3,
    name: "Sporty Alloy Wheels",
    price: 45999,
    category: "exterior",
    model: "altroz",
    image: new URL("../../assets/spoorty wheel.jpg", import.meta.url).href,
    rating: 4.8,
    featured: true,
  },

  {
    id: 4,
    name: "LED Fog Lights",
    price: 7999,
    category: "exterior",
    model: "harrier",
    image: new URL("../../assets/led fog.jpg", import.meta.url).href,

    rating: 4.3,
    featured: false,
  },
  {
    id: 5,
    name: "Wireless Charger",
    price: 5999,
    category: "tech",
    model: "all",
    image: new URL("../../assets/wireless charger.jpg", import.meta.url).href,
    rating: 4.1,
    featured: true,
  },

  {
    id: 6,
    name: "Leather Seat Covers",
    price: 18999,
    category: "interior",
    model: "nexon",
    image: new URL("../../assets/seatcover.jpg", import.meta.url).href,

    rating: 4.7,
    featured: true,
  },
  {
    id: 7,
    name: "Premium Sound System",
    price: 29999,
    category: "tech",
    model: "safari",
    image: new URL("../../assets/sound.jpg", import.meta.url).href,
    rating: 4.6,
    featured: false,
  },
  {
    id: 8,
    name: "Weather Guard Kit",
    price: 8999,
    category: "protection",
    model: "all",
    image: new URL("../../assets/Window Visors.jpeg", import.meta.url).href,

    rating: 4.4,
    featured: true,
  },
  {
    id: 9,
    name: "Chrome Door Handles",
    price: 3499,
    category: "exterior",
    model: "harrier",
    image: new URL("../../assets/door handel.jpg", import.meta.url).href,
    rating: 4.0,
    featured: false,
  },
  {
    id: 10,
    name: "Rear Spoiler",
    price: 11999,
    category: "exterior",
    model: "nexon",
    image: new URL("../../assets/spoiler.webp", import.meta.url).href,
    rating: 4.3,
    featured: true,
  },
  {
    id: 11,
    name: "Dash Cam Pro",
    price: 8999,
    category: "tech",
    model: "all",
    image: new URL("../../assets/car-dash-cam.webp", import.meta.url).href,
    rating: 4.7,
    featured: true,
  },
  {
    id: 12,
    name: "Car Cover Premium",
    price: 7499,
    category: "protection",
    model: "safari",
    image: new URL("../../assets/cover car.jpg", import.meta.url).href,

    rating: 4.2,
    featured: false,
  },
  {
    id: 13,
    name: "Ambient Lighting Kit",
    price: 12999,
    category: "interior",
    model: "altroz",
    image: new URL("../../assets/ambient light kit.jpg", import.meta.url).href,

    rating: 4.6,
    featured: true,
  },
  {
    id: 14,
    name: "TPMS (Tire Pressure Monitor)",
    price: 9999,
    category: "tech",
    model: "all",
    image: new URL(
      "../../assets/TPMS (Tire Pressure Monitor).jpg",
      import.meta.url
    ).href,

    rating: 4.5,
    featured: false,
  },
  {
    id: 15,
    name: "Window Visors",
    price: 5499,
    category: "exterior",
    model: "punch",
    image: new URL("../../assets/weather shield.avif", import.meta.url).href,

    rating: 4.1,
    featured: false,
  },
  {
    id: 16,
    name: "Cargo Organizer",
    price: 3999,
    category: "interior",
    model: "safari",
    image: new URL("../../assets/cargo orgi.jpg", import.meta.url).href,

    rating: 4.4,
    featured: true,
  },
  {
    id: 17,
    name: "Pedal Covers",
    price: 2499,
    category: "interior",
    model: "all",
    image: new URL("../../assets/Pedal Covers.jpg", import.meta.url).href,

    rating: 3.9,
    featured: false,
  },
  {
    id: 18,
    name: "Front Grille Guard",
    price: 18999,
    category: "exterior",
    model: "harrier",
    image: new URL("../../assets/harrier bumper.webp", import.meta.url).href,

    rating: 4.7,
    featured: true,
  },
  {
    id: 19,
    name: "Seat Gap Organizer",
    price: 1499,
    category: "interior",
    model: "all",
    image: new URL("../../assets/Seat Gap Organizer.jpg", import.meta.url).href,

    rating: 4.0,
    featured: false,
  },
  {
    id: 20,
    name: "Rear Entertainment System",
    price: 34999,
    category: "tech",
    model: "safari",
    image: new URL("../../assets/infodianam.jpg", import.meta.url).href,

    rating: 4.8,
    featured: true,
  },
  {
    id: 21,
    name: "Side Steps",
    price: 23999,
    category: "exterior",
    model: "safari",
    image: new URL("../../assets/safari side stand.jpg", import.meta.url).href,

    rating: 4.5,
    featured: true,
  },
  {
    id: 22,
    name: "Steering Wheel Cover",
    price: 1999,
    category: "interior",
    model: "all",
    image: new URL("../../assets/Steering Wheel Cover.jpeg", import.meta.url)
      .href,

    rating: 3.8,
    featured: false,
  },
  {
    id: 23,
    name: "Emergency Kit",
    price: 2999,
    category: "protection",
    model: "all",
    image: new URL("../../assets/emergengy kit.avif", import.meta.url).href,

    rating: 4.6,
    featured: true,
  },
];
export const categories = [
  { id: "all", name: "All Accessories" },
  { id: "interior", name: "Interior" },
  { id: "exterior", name: "Exterior" },
  { id: "tech", name: "Technology" },
  { id: "protection", name: "Protection" },
];

export const carModels = [
  { id: "all", name: "All Models" },
  { id: "nexon", name: "Nexon" },
  { id: "harrier", name: "Harrier" },
  { id: "safari", name: "Safari" },
  { id: "altroz", name: "Altroz" },
  { id: "tiago", name: "Tiago" },
  { id: "tigor", name: "Tigor" },
  { id: "punch", name: "Punch" },
  { id: "curvv", name: "Curvv" },
];

export const sortOptions = [
  { id: "featured", name: "Featured" },
  { id: "price-low", name: "Price: Low to High" },
  { id: "price-high", name: "Price: High to Low" },
  { id: "rating", name: "Top Rated" },
];
